# __init__.py

import os
from .simple_load_image_batch import NODE_CLASS_MAPPINGS as SIMPLE_LOAD_IMAGE_BATCH_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_LOAD_IMAGE_BATCH_DISPLAY_MAPPINGS
from .queue_control_node import VrchCountdownQueueControlNode
from .crop_transparent_node import NODE_CLASS_MAPPINGS as CROP_TRANSPARENT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CROP_TRANSPARENT_DISPLAY_MAPPINGS
from .crop_black_and_white_borders_node import NODE_CLASS_MAPPINGS as CROP_BLACK_WHITE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CROP_BLACK_WHITE_DISPLAY_MAPPINGS
from .save_image_node import NODE_CLASS_MAPPINGS as SAVE_IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAVE_IMAGE_DISPLAY_NAME_MAPPINGS
from .remove_background_node import NODE_CLASS_MAPPINGS as ISOLATE_COLOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ISOLATE_COLOR_DISPLAY_NAME_MAPPINGS
from .image_switch_node import ImageSwitchNode
from .conditional_save_image_node import NODE_CLASS_MAPPINGS as CONDITIONAL_SAVE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONDITIONAL_SAVE_DISPLAY_MAPPINGS
from .image_processor import NODE_CLASS_MAPPINGS as Image_Processor_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as Image_Processor_DISPLAY_MAPPINGS
from .load_rgba_image_node import NODE_CLASS_MAPPINGS as LOAD_RGBA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_RGBA_DISPLAY_MAPPINGS
from .crop_transparent_and_resize_node import NODE_CLASS_MAPPINGS as CROP_TRANSPARENT_RESIZE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CROP_TRANSPARENT_RESIZE_DISPLAY_MAPPINGS
from .stretch_bottom_node import NODE_CLASS_MAPPINGS as STRETCH_BOTTOM_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STRETCH_BOTTOM_DISPLAY_MAPPINGS
from .expand_transparent_border_node import NODE_CLASS_MAPPINGS as EXPAND_TRANSPARENT_BORDER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EXPAND_TRANSPARENT_BORDER_DISPLAY_MAPPINGS
from .counter_node import NODE_CLASS_MAPPINGS as COUNTER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COUNTER_DISPLAY_MAPPINGS
from .sequential_reader_node import NODE_CLASS_MAPPINGS as SEQ_READER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SEQ_READER_DISPLAY_MAPPINGS
from .split_transparent_node import NODE_CLASS_MAPPINGS as SPLIT_TRANSPARENT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SPLIT_TRANSPARENT_DISPLAY_MAPPINGS
from .countdown_state_switcher import NODE_CLASS_MAPPINGS as COUNTDOWN_SWITCHER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COUNTDOWN_SWITCHER_DISPLAY_MAPPINGS
from .save_text_node import NODE_CLASS_MAPPINGS as SAVE_TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAVE_TEXT_DISPLAY_MAPPINGS
from .random_number_node import NODE_CLASS_MAPPINGS as RANDOM_NUMBER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RANDOM_NUMBER_DISPLAY_MAPPINGS
from .smart_resize_pad import NODE_CLASS_MAPPINGS as SMART_RESIZE_PAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SMART_RESIZE_PAD_DISPLAY_MAPPINGS

# =======================================
# 导入精简版文本节点
# =======================================
from .text_utils_nodes import UniversalTextReplacer

# 定义新节点的映射
TEXT_UTILS_NODE_CLASS_MAPPINGS = {
    "UniversalTextReplacer": UniversalTextReplacer
}

TEXT_UTILS_NODE_DISPLAY_NAME_MAPPINGS = {
    "UniversalTextReplacer": "通用文本替换"
}


NODE_CLASS_MAPPINGS = {
    **SIMPLE_LOAD_IMAGE_BATCH_MAPPINGS,
    "VrchCountdownQueueControlNode": VrchCountdownQueueControlNode,
    **CROP_TRANSPARENT_MAPPINGS,
    **CROP_BLACK_WHITE_MAPPINGS,
    **SAVE_IMAGE_MAPPINGS,
    **ISOLATE_COLOR_MAPPINGS,
    "ImageSwitchNode": ImageSwitchNode,
    **CONDITIONAL_SAVE_MAPPINGS,
    **Image_Processor_MAPPINGS,
    **LOAD_RGBA_MAPPINGS,
    **CROP_TRANSPARENT_RESIZE_MAPPINGS,
    **STRETCH_BOTTOM_MAPPINGS,
    **EXPAND_TRANSPARENT_BORDER_MAPPINGS,
    **COUNTER_MAPPINGS,
    **SEQ_READER_MAPPINGS,
    **SPLIT_TRANSPARENT_MAPPINGS,
    **COUNTDOWN_SWITCHER_MAPPINGS,
    **RANDOM_NUMBER_MAPPINGS,
    **SAVE_TEXT_MAPPINGS,
    **TEXT_UTILS_NODE_CLASS_MAPPINGS,  # 注册新节点
    **SMART_RESIZE_PAD_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SIMPLE_LOAD_IMAGE_BATCH_DISPLAY_MAPPINGS,
    "VrchCountdownQueueControlNode": "队列管理",
    **CROP_TRANSPARENT_DISPLAY_MAPPINGS,
    **CROP_BLACK_WHITE_DISPLAY_MAPPINGS,
    **SAVE_IMAGE_DISPLAY_NAME_MAPPINGS,
    **ISOLATE_COLOR_DISPLAY_NAME_MAPPINGS,
    "ImageSwitchNode": "图像切换",
    **CONDITIONAL_SAVE_DISPLAY_MAPPINGS,
    **Image_Processor_DISPLAY_MAPPINGS,
    **LOAD_RGBA_DISPLAY_MAPPINGS,
    **CROP_TRANSPARENT_RESIZE_DISPLAY_MAPPINGS,
    **STRETCH_BOTTOM_DISPLAY_MAPPINGS,
    **EXPAND_TRANSPARENT_BORDER_DISPLAY_MAPPINGS,
    **COUNTER_DISPLAY_MAPPINGS,
    **SEQ_READER_DISPLAY_MAPPINGS,
    **SPLIT_TRANSPARENT_DISPLAY_MAPPINGS,
    **COUNTDOWN_SWITCHER_DISPLAY_MAPPINGS,
    **RANDOM_NUMBER_DISPLAY_MAPPINGS,
    **SAVE_TEXT_DISPLAY_MAPPINGS,
    **TEXT_UTILS_NODE_DISPLAY_NAME_MAPPINGS, # 注册新节点显示名称
    **SMART_RESIZE_PAD_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = os.path.join(os.path.dirname(os.path.realpath(__file__)), "js")

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
