# Namespace package for image nodes.

from ..api.seedream_ark_node import (
    NODE_CLASS_MAPPINGS as SEEDREAM_ARK_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEEDREAM_ARK_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **SEEDREAM_ARK_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SEEDREAM_ARK_DISPLAY_MAPPINGS,
}
